title: "FlowformLab"
tagline: "Notes on systems, tools, and the process of figuring things out (mostly for myself)."
description: "FlowformLab is a personal journal on how things work — and how to make them work better (or at least, better for me). It’s my working log—part notes, part diagrams, part reflection—where I trace ideas as they flow, form, and evolve."
email: spark@flowformlab.com

url: https://flowformlab.com
baseurl: ""          # keep empty for apex domain

# Theme & plugins
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

# ------------------------------------------------------------
# Default settings for new posts and pages
# ------------------------------------------------------------
defaults:
  # Applies to all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
