title: FlowformLab
description: "Structured reflections on digital transformation and delivery practices — mapping risks, mitigations, and lessons learned."
email: spark@example.com
url: https://your-username.github.io
baseurl: ""


remote_theme: mmistakes/minimal-mistakes
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-include-cache


locale: en
header_pages:
- about.md
- contact.md


markdown: kramdown
permalink: "/:categories/:year/:month/:day/:title/"


defaults:
- scope:
path: ""
type: posts
values:
layout: single
author_profile: false
read_time: false
comments: false
share: false
- scope:
path: ""
type: pages
values:
layout: single
author_profile: false
- Gemfile.lock
