title: "FlowformLab"
tagline: "Notes on systems, tools, and the process of figuring things out (mostly for myself)."
description: "FlowformLab is a personal journal on how things work — and how to make them work better (or at least, better for me). It’s my working log—part notes, part diagrams, part reflection—where I trace ideas as they flow, form, and evolve."
email: spark@flowformlab.com

# If you’re using the custom domain (recommended since you set DNS):
url: https://flowformlab.com
baseurl: ""          # keep empty for apex domain

# Theme & plugins
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-sitemap

# ------------------------------------------------------------
# Default settings for new posts and pages
# ------------------------------------------------------------
defaults:
  # Applies to all posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
  # Applies to pages (like about.md)
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

locale: en

#logo assets
logo: /assets/images/logo-ffl-spark.svg

# Markdown & permalinks
markdown: kramdown
permalink: "/:categories/:year/:month/:day/:title/"

# Defaults (note the indentation)
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: false
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

# Exclude files from the site build
exclude:
  - README.md
  - .github/
  - Gemfile
  - Gemfile.lock
